#!/usr/bin/env bash
# Jenkins Pipeline Setup - Visual Guide & Status Check
# Run this to see all available files and their status

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Jenkins CI/CD Pipeline Setup - Complete Package              ║"
echo "║  Status: ✅ Ready to Deploy                                   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 CORE FILES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🟢 Jenkinsfile                      Production-ready pipeline"
echo "  🟢 docker-compose.yml               Docker-based setup"
echo "  🟢 jenkins.yaml                     Configuration as Code"
echo ""
echo "📚 DOCUMENTATION (Read in Order)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⭐ JENKINS_QUICKSTART.md            ← START HERE (5 min read)"
echo "     │ Installation & first pipeline"
echo "     │"
echo "  📖 JENKINS_DOCUMENTATION_INDEX.md   Navigation & roadmap"
echo "     │"
echo "  📖 JENKINS_SETUP.md                 Complete setup guide"
echo "     │ (30 min deep dive)"
echo "     │"
echo "  📖 PIPELINE_EXAMPLES.md             20+ code examples"
echo "     │ (Patterns & best practices)"
echo "     │"
echo "  🆘 TROUBLESHOOTING.md               Issue solutions"
echo "     │ (Reference when stuck)"
echo "     │"
echo "  📋 JENKINS_PIPELINE_SUMMARY.md      Overview & checklist"
echo ""
echo "🔧 AUTOMATION SCRIPTS (Executable)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⚙️  setup-jenkins.sh                Automated setup"
echo "     Usage: ./setup-jenkins.sh"
echo "     Does:  Install Jenkins, Java, Maven"
echo ""
echo "  ⚙️  configure-jenkins-plugins.sh    Plugin installer"
echo "     Usage: ./configure-jenkins-plugins.sh"
echo "     Does:  Install 15+ essential plugins"
echo ""
echo "📊 ARCHITECTURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Git Trigger (Webhook/Manual)"
echo "        ↓"
echo "  Jenkins Pipeline"
echo "    ├─ Checkout Code"
echo "    ├─ Build"
echo "    ├─ Unit Tests"
echo "    ├─ Integration Tests"
echo "    ├─ Code Quality"
echo "    ├─ Deployment"
echo "    ├─ Smoke Tests"
echo "    └─ Reports & Notifications"
echo ""
echo "🚀 QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1️⃣  Read This First:"
echo "     open JENKINS_QUICKSTART.md"
echo ""
echo "  2️⃣  Run Setup Script:"
echo "     chmod +x setup-jenkins.sh"
echo "     ./setup-jenkins.sh"
echo ""
echo "  3️⃣  Open Jenkins:"
echo "     open http://localhost:8080"
echo ""
echo "  4️⃣  Complete Web Setup:"
echo "     - Paste admin password"
echo "     - Install plugins"
echo "     - Create user"
echo ""
echo "  5️⃣  Add GitHub Credentials"
echo ""
echo "  6️⃣  Create Pipeline Job"
echo ""
echo "  7️⃣  Run First Build"
echo ""
echo "⏱️  TIME ESTIMATE: ~30 minutes total"
echo ""
echo "✨ KEY FEATURES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ Full CI/CD pipeline"
echo "  ✅ Multi-stage build (Build → Test → Deploy)"
echo "  ✅ Parallel test execution"
echo "  ✅ Code quality analysis ready"
echo "  ✅ Email & Slack notifications"
echo "  ✅ Artifact archival"
echo "  ✅ GitHub integration"
echo "  ✅ Docker support"
echo "  ✅ Configuration as Code"
echo "  ✅ Security best practices"
echo ""
echo "📋 FILE SIZES & LINES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
wc -l Jenkinsfile JENKINS_QUICKSTART.md JENKINS_SETUP.md \
     PIPELINE_EXAMPLES.md TROUBLESHOOTING.md jenkins.yaml \
     docker-compose.yml setup-jenkins.sh configure-jenkins-plugins.sh \
     2>/dev/null | tail -1 | awk '{print "  Total: " $1 " lines of content & config"}'
echo ""
echo "🎯 NEXT STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Recommended reading order:"
echo "  1. JENKINS_QUICKSTART.md (5 min) - Get started"
echo "  2. Run setup-jenkins.sh - Automated installation"
echo "  3. Complete Jenkins web setup (3 min)"
echo "  4. Create first pipeline job (5 min)"
echo "  5. Run test build (5 min)"
echo "  6. Read JENKINS_SETUP.md - Deep dive into features"
echo "  7. Study PIPELINE_EXAMPLES.md - Learn patterns"
echo ""
echo "🆘 NEED HELP?"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Problem                        Solution Document"
echo "  ─────────────────────────────  ─────────────────────────"
echo "  Jenkins won't start            TROUBLESHOOTING.md"
echo "  Tests fail in pipeline         TROUBLESHOOTING.md"
echo "  GitHub not connecting          TROUBLESHOOTING.md"
echo "  Want to understand Jenkinsfile PIPELINE_EXAMPLES.md"
echo "  Need advanced features         JENKINS_SETUP.md"
echo ""
echo "📂 PROJECT STRUCTURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ls -lh Jenkinsfile docker-compose.yml jenkins.yaml 2>/dev/null | \
  awk '{print "  " $9 " (" $5 ")"}' | grep -v "^  ()"
echo ""
ls -lh JENKINS_*.md 2>/dev/null | \
  awk '{print "  " $9 " (" $5 ")"}' | grep -v "^  ()"
echo ""
ls -lh PIPELINE_*.md TROUBLESHOOTING.md 2>/dev/null | \
  awk '{print "  " $9 " (" $5 ")"}' | grep -v "^  ()"
echo ""
ls -lh *.sh 2>/dev/null | \
  awk '{print "  " $9 " (" $5 ")"}' | grep -v "^  ()"
echo ""
echo "✅ STATUS: All files created and ready!"
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  👉 Next: Read JENKINS_QUICKSTART.md and run setup-jenkins.sh ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
